plugins {
    id 'application'
    id 'java'
    id 'jacoco'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.fusesource.jansi:jansi:2.4.0'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    testLogging {
        events "passed", "skipped", "failed"
    }
}

jacocoTestReport {
    dependsOn test
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                counter = 'INSTRUCTION'
                value = 'COVEREDRATIO'
                minimum = 0.50
            }
        }
    }
}

application {
    mainClass = 'dungeonmeshigame.App'
}

run {
    standardInput = System.in
}

javadoc {
    destinationDir = file("${buildDir}/docs/javadoc")
    options.memberLevel = JavadocMemberLevel.PRIVATE
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
    options.addBooleanOption('private', true)
}